### ISSUE TITLE
issue for adding a custom op with bazel 

### ISSUE THREAD

**Issue by qixuxiang** [cgtuebingen/tf_custom_op#1]
Hi ,thanks for your awesome code share!

Yesterday I attempted to use your code to add a custom op with bazel(not  cmake), the code is [here](https://github.com/qixuxiang/bazel_tf_op). I pass all the compilations but  there is a link error named `undefined symbol: _ZN10tensorflow7functor`, Would you please help me if you have spare time? Thanks a lot!

**Comment by qixuxiang** [comment]
@cgtuebingen   I saw lots of alike issues of it, such as [#1](https://stackoverflow.com/questions/51201547/tensorflow-undefined-symbol-when-loading-custom-gpu-op), [#2](https://github.com/tensorflow/tensorflow/issues/10714)  and [#3](https://github.com/tensorflow/tensorflow/issues/2455), the common solution is add `add the -D_GLIBCXX_USE_CXX11_ABI=0` flag or use GCC4, but it doen not work. I am very appreciated if you can help me ~~

**Comment by qixuxiang** [comment]
Thanks a lot anyway,  I want to add a custom op with bazel independent of the TensorFlow source, but it is really difficult. This is my error details:

```
root@de16c859cd6c:/usr/Downloads# bazel build --config=monolithic --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt="-fPIC"  --linkopt="/usr/local/lib/python2.7/dist-packages/tensorflow/libtensorflow_framework.so" op:matrix_add_op 
WARNING: Config values are not defined in any .rc file: monolithic
WARNING: /root/.cache/bazel/_bazel_root/c75888d4fb7292147ded22c00064e0e3/external/tf/BUILD.bazel:8:12: in hdrs attribute of cc_library rule @tf//:main: file '_api_implementation.so' from target '@tf//:include/external/protobuf_archive/python/google/protobuf/internal/_api_implementation.so' is not allowed in hdrs
WARNING: /root/.cache/bazel/_bazel_root/c75888d4fb7292147ded22c00064e0e3/external/tf/BUILD.bazel:8:12: in hdrs attribute of cc_library rule @tf//:main: file '_message.so' from target '@tf//:include/external/protobuf_archive/python/google/protobuf/pyext/_message.so' is not allowed in hdrs
INFO: Analysed target //op:matrix_add_op (8 packages loaded).
INFO: Found 1 target...
Target //op:matrix_add_op up-to-date:
  bazel-bin/op/libmatrix_add_op.a
  bazel-bin/op/libmatrix_add_op.so
INFO: Elapsed time: 4.576s, Critical Path: 2.42s
INFO: Build completed successfully, 1 total action
root@de16c859cd6c:/usr/Downloads# python op/__init__.py
Traceback (most recent call last):
  File "op/__init__.py", line 11, in <module>
    _matrix_add_module = tf.load_op_library('/usr/Downloads/bazel-bin/op/libmatrix_add_op.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/Downloads/bazel-bin/op/libmatrix_add_op.so: undefined symbol: _ZN10tensorflow7functor13MatrixAddGradIN5Eigen9GpuDeviceEdEclEPNS_15OpKernelContextERKNS_6TensorEPS7_SA_

```

**Comment by PatWie** [comment]
And that's why I am using Cmake, which is straightforward. In your case you don't link the matrix_add_kernel.cu file.
